### ISSUE TITLE
Typo in base.py?  deamon should be daemon

### ISSUE THREAD

**Issue by jkuzeja** [pepijndevos/PyMouse#1]
Not sure how important this is, but I noticed that in PyMouseEventMeta.**init** in base.py, daemon is spelled "deamon".  If this is an intentional misspelling, then it needs a comment at least :)
-Jim

**Comment by pepijndevos** [comment]
I'll have a look at it. I think this means PyMouse will by default not run in daemon mode because of this typo. The truth is that I never realized deamon is actually spelled daemon, even though deamon has a red line under it. Thanks for taking the time to browse through the source code.
