### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by waspinator** [pepijndevos/PyMouse#3]
I'm new to python and can't seem to find out how to "put the python files somewhere on the python path". I'm using Ubuntu 10.10, which uses python 2.6.6. Tried v1.0 and master.

setup.py give errors (even after installing python-setuptools ... which I'm not even sure is what is needed)
    from: can't read /var/mail/distutils.core
    ./setup.py: line 19: syntax error near unexpected token `name='PyMouse','
    ./setup.py: line 19:`setup(name='PyMouse','

trying to add the pymouse directory to sys.path also did not work for me:
    >>> import sys
    >>> sys.path.append("/home/username/pymouse")
    >>> from pymouse import PyMouse
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "pymouse/**init**.py", line 95, in <module>
        from unix import PyMouse, PyMouseEvent
      File "pymouse/unix.py", line 17, in <module>
        from Xlib.display import Display
    ImportError: No module named Xlib.display

Can I get some hand-holding instructions on how to use this?
Thanks

**Comment by ponty** [comment]
try this:

```
sudo apt-get install  python-xlib
sudo easy_install https://github.com/pepijndevos/PyMouse/zipball/master
```

**Comment by waspinator** [comment]
Thanks, that worked for me. I'll add this to the wiki.
